# app.yaml

# service: exercises
runtime: nodejs16

instance_class: F1
automatic_scaling:
  max_instances: 10
  min_instances: 0

env_variables:
  CORS_URL: "*"
  ACCESS_TOKEN_VALIDITY_DAYS: 30
  REFRESH_TOKEN_VALIDITY_DAYS: 120
  TOKEN_ISSUER: "https://grow-crm.web.app"
  TOKEN_AUDIENCE: "https://grow-crm.web.app"

entrypoint: "node build/src/server.js"