steps:
  - name: node:18.19.0
    entrypoint: yarn
    args: ["install"]
  - name: ubuntu
    entrypoint: bash
    args:
      - -c
      - apt-get update > /dev/null && 
        apt-get install -y curl gnupg > /dev/null &&
        (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh &&
        doppler run -- yarn build;
    env:
      - DOPPLER_TOKEN=$_DOPPLER_TOKEN
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "--quiet",
        "app.yaml",
        "--project",
        "regal-operations-staging",
        "--version",
        "service-default",
        "--no-promote"
      ]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
