steps:
  - name: node:16.14.0
    entrypoint: yarn
    args: ["install"]
  - name: node:16.14.0
    entrypoint: yarn
    args: ["build"]
  - name: node:16.14.0
    entrypoint: yarn
    args: ["create-env"]
    env:
      - "DB_NAME=${_DB_NAME}"
      - "DB_USER=${_DB_USER}"
      - "DB_USER_PWD=${_DB_USER_PWD}"
      - "DB_HOST=${_DB_HOST}"
      - "FIREBASE_DB_HOST=${_FIREBASE_DB_HOST}"
      - "WC_CONSUMER_KEY=${_WC_CONSUMER_KEY}"
      - "WC_CONSUMER_SECRET=${_WC_CONSUMER_SECRET}"
      - "JWT_SIGNATURE_SECRET=${_JWT_SIGNATURE_SECRET}"
      - "MAILJET_API_KEY=${_MAILJET_API_KEY}"
      - "MAILJET_SECRET_KEY=${_MAILJET_SECRET_KEY}"
      - "PAYSTACK_SECRET_KEY=${_PAYSTACK_SECRET_KEY}"
      - "MONNIFY_API_KEY=${_MONNIFY_API_KEY}"
      - "MONNIFY_SECRET_KEY=${_MONNIFY_SECRET_KEY}"
      - "MONNIFY_BASE_URL=${_MONNIFY_BASE_URL}"
      - "PAYPAL_CLIENT_ID=${_PAYPAL_CLIENT_ID}"
      - "PAYPAL_CLIENT_SECRET=${_PAYPAL_CLIENT_SECRET}"
      - "PAYPAL_BASE_URL=${_PAYPAL_BASE_URL}"
      - "API_LAYER_KEY=${_API_LAYER_KEY}"
      - "FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
      - "TINIFY_KEY=${_TINIFY_KEY}"
      - "WC_CONSUMER_KEY_FLORAL=${_WC_CONSUMER_KEY_FLORAL}"
      - "WC_CONSUMER_SECRET_FLORAL=${_WC_CONSUMER_SECRET_FLORAL}"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "--quiet",
        "app.yaml",
        "--project",
        "regal-operations-defy",
        "--version",
        "service-default",
        "--no-promote"
      ]
timeout: "1600s"
