# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Perform build
        run: yarn build
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          version: "service-default"
          promote: false